<a href="https://colab.research.google.com/github/sayalidudhane/machinelearning/blob/main/Pca2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import seaborn as sns
import matplotlib.pyplot as plt
import math

In [4]:
df = pd.read_csv('/content/chd.csv')
df.head()

Obs  ID  AGE  agrp  CHD
0    1   1   20     1    0
1    2   2   23     1    0
2    3   3   24     1    0
3    4   4   25     1    0
4    5   5   25     1    1

In [5]:
df.describe()

Obs          ID         AGE        agrp        CHD
count  100.000000  100.000000  100.000000  100.000000  100.00000
mean    50.500000   50.500000   44.380000    4.480000    0.43000
std     29.011492   29.011492   11.721327    2.240491    0.49757
min      1.000000    1.000000   20.000000    1.000000    0.00000
25%     25.750000   25.750000   34.750000    2.750000    0.00000
50%     50.500000   50.500000   44.000000    4.000000    0.00000
75%     75.250000   75.250000   55.000000    7.000000    1.00000
max    100.000000  100.000000   69.000000    8.000000    1.00000

In [6]:
endog = df['agrp'].head(4)
exog =  df[['Obs','ID','AGE']].head(4)
print(exog)

   Obs  ID  AGE
0    1   1   20
1    2   2   23
2    3   3   24
3    4   4   25


In [7]:
X=exog.to_numpy()
Y= endog.to_numpy()
print(X)

[[ 1  1 20]
 [ 2  2 23]
 [ 3  3 24]
 [ 4  4 25]]


In [8]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [9]:
M = mean(X.T, axis=1)
print(M)

[ 2.5  2.5 23. ]


In [10]:
C= X-M
print(C)

[[-1.5 -1.5 -3. ]
 [-0.5 -0.5  0. ]
 [ 0.5  0.5  1. ]
 [ 1.5  1.5  2. ]]


In [11]:
V = cov(C.T)
print(V)

[[1.66666667 1.66666667 2.66666667]
 [1.66666667 1.66666667 2.66666667]
 [2.66666667 2.66666667 4.66666667]]


In [12]:
values, vectors = eig(V)
print(vectors)
print(values)

[[-4.54401349e-01 -7.07106781e-01 -5.41774320e-01]
 [-4.54401349e-01  7.07106781e-01 -5.41774320e-01]
 [-7.66184591e-01  2.03840233e-15  6.42620551e-01]]
[ 7.82970843e+00 -4.48442806e-16  1.70291569e-01]


In [13]:
P = vectors.T.dot(C.T)
print(P.T)

[[ 3.66175782e+00 -1.11920338e-15 -3.02538691e-01]
 [ 4.54401349e-01  1.66533454e-15  5.41774320e-01]
 [-1.22058594e+00  3.73067794e-16  1.00846230e-01]
 [-2.89557323e+00 -9.19198948e-16 -3.40081859e-01]]


In [14]:
from sklearn.decomposition import PCA
pca = PCA(n_components=1)
principalComponents = pca.fit_transform(X)
principalDf = pd.DataFrame(data = principalComponents,columns = ['principal component 1'])

In [15]:
exog1 = sm.add_constant(principalDf[['principal component 1']])
print(exog1)

   const  principal component 1
0    1.0               3.661758
1    1.0               0.454401
2    1.0              -1.220586
3    1.0              -2.895573


In [16]:
from sklearn import linear_model
lm = linear_model.LinearRegression()
model = lm.fit(exog1,endog)
lm.coef_

array([0., 0.])

In [17]:
lm.intercept_

1.0

In [19]:
def RSE(y_true, y_predicted):
       
    y_true = np.array(y_true)
    y_predicted = np.array(y_predicted)
    RSS = np.sum(np.square(y_true - y_predicted))
    rse = math.sqrt(RSS / (len(y_true) - 2))
    return rse

In [21]:
ypred =lm.predict(exog1)

In [22]:
re = RSE(endog,ypred)
print(re)

0.0
